### ISSUE TITLE
Error in msprime Out-of-Africa model

### ISSUE THREAD

**Issue by jeromekelleher** [Ephraim-usc/egrm#1]
We have recently learned that there was an error in the description of the Gutenkunst et al model provided as an example in the msprime tutorial. It appears that you are using a copy of the incorrect model in this repo, and so I am opening this issue to alert you. 

Please see [here](https://github.com/jeromekelleher/msprime-model-errors) for details on what the error is, and what actions you can take to fix it.

We have also written a [short note](https://github.com/jeromekelleher/msprime-model-errors/raw/master/paper.pdf) analysing this and another related error, detailing the likely effects on downstream analysis. Thankfully, the differences between the misspecified model from msprime's documentation and the intended model are slight.

I apologise for this error and I sincerely hope that it has not affected your research.

**Comment by Ephraim-usc** [comment]
Thank you for alerting us! We did copy code from the old version msprime tutorial, but our simulations only used the demography of the European branch of the OOA model. If the error is on the migration rate, it shouldn't have any impact on our simulations. Do we understand it right? Thank you.

**Comment by Ephraim-usc** [comment]
> We have recently learned that there was an error in the description of the Gutenkunst et al model provided as an example in the msprime tutorial. It appears that you are using a copy of the incorrect model in this repo, and so I am opening this issue to alert you.
> 
> Please see [here](https://github.com/jeromekelleher/msprime-model-errors) for details on what the error is, and what actions you can take to fix it.
> 
> We have also written a [short note](https://github.com/jeromekelleher/msprime-model-errors/raw/master/paper.pdf) analysing this and another related error, detailing the likely effects on downstream analysis. Thankfully, the differences between the misspecified model from msprime's documentation and the intended model are slight.
> 
> I apologise for this error and I sincerely hope that it has not affected your research.

**Comment by jeromekelleher** [comment]
Unfortunately I think it can still have an effect on your simulations, even if you just sample from the European population @Ephraim-usc, because the ancestral population sizes experience by old lineages will be different to what they should have been under the correct model. Fig 1A and B are helpful to visualise this.

However, I would expect the effect to be quite subtle.
